from Application.Services.WriteData.WriteOfflineData.WriteOfflineDataIndexService import write_offline_data_index
from Application.Services.WriteData.WriteOfflineData.WriteOfflineDataStockService import write_offline_data_stock
from writeChromeExtensionJson import write_chrome_extension_json
#
# write_offline_data_index()
write_offline_data_stock()
# write_chrome_extension_json()
